/* eslint-disable unicorn/filename-case */
export const SET_BUSINESS_SELECTED = 'BUSINESS_SELECTED';
export const SET_SEARCH_BUSINESS_NAME = 'SET_SEARCH_BUSINESS_NAME';
export const SET_BUSINESS_SERVICES_SELECTED = 'SET_BUSINESS_SERVICES_SELECTED';
