/* eslint-disable unicorn/filename-case */
export const SET_BUSINESS_SELECTED = 'BUSINESS_SELECTED';
export const SET_SEARCH_BUSINESS_NAME = 'SET_SEARCH_BUSINESS_NAME';
export const SET_BUSINESS_SERVICES_SELECTED = 'SET_BUSINESS_SERVICES_SELECTED';
export const SET_APPOINTMENT_TIME = 'SET_APPOINTMENT_TIME';
export const SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED';
export const SET_DETAIL_SERVICES = 'SET_DETAIL_SERVICES';
